import Head from 'next/head';
import Image from 'next/image';
import About from '../components/About/About';
import Contacts from '../components/Contacts/Contacts';
import Education from '../components/Education/Education';
import Intro from '../components/Intro/Intro';
import Navigation from '../components/Navigation/Navigation';
import Portfolio from '../components/Portfolio/Portfolio';
import Skills from '../components/Skills/Skills';
import styles from '../styles/Home.module.scss';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kholod Ihor Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <Navigation />
      </header>

      <main className={styles.main}>
        <Intro />
        <About/>
        <Education/>
        <Skills/>
        <Portfolio/>
        <Contacts/>
      </main>

    </div>
  );
}
